set_property SRC_FILE_INFO {cfile:/nfs/ug/homes-0/y/yangqiu/Desktop/fix_cam/worked_cam/worked_cam.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0.xdc rfile:../../../worked_cam.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0.xdc id:1 order:EARLY scoped_inst:design_1_i/microblaze_0/U0} [current_design]
set_property SRC_FILE_INFO {cfile:/nfs/ug/homes-0/y/yangqiu/Desktop/fix_cam/worked_cam/worked_cam.srcs/sources_1/bd/design_1/ip/design_1_mdm_1_0/design_1_mdm_1_0.xdc rfile:../../../worked_cam.srcs/sources_1/bd/design_1/ip/design_1_mdm_1_0/design_1_mdm_1_0.xdc id:2 order:EARLY scoped_inst:design_1_i/mdm_1/U0} [current_design]
set_property SRC_FILE_INFO {cfile:/nfs/ug/homes-0/y/yangqiu/Desktop/fix_cam/worked_cam/worked_cam.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1_0/design_1_clk_wiz_1_0.xdc rfile:../../../worked_cam.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1_0/design_1_clk_wiz_1_0.xdc id:3 order:EARLY scoped_inst:design_1_i/clk_wiz_1/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/nfs/ug/homes-0/y/yangqiu/Desktop/fix_cam/worked_cam/worked_cam.srcs/sources_1/bd/design_1/ip/design_1_mig_7series_0_0/design_1_mig_7series_0_0/user_design/constraints/design_1_mig_7series_0_0.xdc rfile:../../../worked_cam.srcs/sources_1/bd/design_1/ip/design_1_mig_7series_0_0/design_1_mig_7series_0_0/user_design/constraints/design_1_mig_7series_0_0.xdc id:4 order:EARLY scoped_inst:design_1_i/mig_7series_0} [current_design]
set_property SRC_FILE_INFO {cfile:/nfs/ug/homes-0/y/yangqiu/Desktop/fix_cam/worked_cam/worked_cam.srcs/sources_1/bd/design_1/ip/design_1_ov7670_top_0_0/src/clk_wiz_0/clk_wiz_0.xdc rfile:../../../worked_cam.srcs/sources_1/bd/design_1/ip/design_1_ov7670_top_0_0/src/clk_wiz_0/clk_wiz_0.xdc id:5 order:EARLY scoped_inst:design_1_i/ov7670_top_0/inst/u_clock/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/nfs/ug/homes-0/y/yangqiu/Desktop/fix_cam/worked_cam/worked_cam.srcs/constrs_1/new/constraints.xdc rfile:../../../worked_cam.srcs/constrs_1/new/constraints.xdc id:6} [current_design]
set_property SRC_FILE_INFO {cfile:/nfs/ug/homes-0/y/yangqiu/Desktop/fix_cam/worked_cam/worked_cam.srcs/sources_1/bd/design_1/ip/design_1_axis_data_fifo_0_0/design_1_axis_data_fifo_0_0/design_1_axis_data_fifo_0_0_clocks.xdc rfile:../../../worked_cam.srcs/sources_1/bd/design_1/ip/design_1_axis_data_fifo_0_0/design_1_axis_data_fifo_0_0/design_1_axis_data_fifo_0_0_clocks.xdc id:7 order:LATE scoped_inst:design_1_i/axis_data_fifo_0/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/nfs/ug/homes-0/y/yangqiu/Desktop/fix_cam/worked_cam/worked_cam.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_0/design_1_auto_cc_0_clocks.xdc rfile:../../../worked_cam.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_0/design_1_auto_cc_0_clocks.xdc id:8 order:LATE scoped_inst:design_1_i/axi_mem_intercon/m00_couplers/auto_cc/inst} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_ip_msg_config -idlist { DPOP-3 PDCN-1569 CDC-1 CDC-4 CDC-7 TIMING-9 TIMING-10 }
set_property src_info {type:SCOPED_XDC file:2 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_ip_msg_config -idlist { CDC-1 CDCM-1 REQP-1851 TIMING-2 TIMING-4 TIMING-9 TIMING-10 TIMING-14 }
set_property src_info {type:SCOPED_XDC file:3 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.1
set_property src_info {type:SCOPED_XDC file:4 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R7 [get_ports {ddr2_dq[0]}]
set_property src_info {type:SCOPED_XDC file:4 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V6 [get_ports {ddr2_dq[1]}]
set_property src_info {type:SCOPED_XDC file:4 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R8 [get_ports {ddr2_dq[2]}]
set_property src_info {type:SCOPED_XDC file:4 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U7 [get_ports {ddr2_dq[3]}]
set_property src_info {type:SCOPED_XDC file:4 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V7 [get_ports {ddr2_dq[4]}]
set_property src_info {type:SCOPED_XDC file:4 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R6 [get_ports {ddr2_dq[5]}]
set_property src_info {type:SCOPED_XDC file:4 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U6 [get_ports {ddr2_dq[6]}]
set_property src_info {type:SCOPED_XDC file:4 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R5 [get_ports {ddr2_dq[7]}]
set_property src_info {type:SCOPED_XDC file:4 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T5 [get_ports {ddr2_dq[8]}]
set_property src_info {type:SCOPED_XDC file:4 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U3 [get_ports {ddr2_dq[9]}]
set_property src_info {type:SCOPED_XDC file:4 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V5 [get_ports {ddr2_dq[10]}]
set_property src_info {type:SCOPED_XDC file:4 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U4 [get_ports {ddr2_dq[11]}]
set_property src_info {type:SCOPED_XDC file:4 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V4 [get_ports {ddr2_dq[12]}]
set_property src_info {type:SCOPED_XDC file:4 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T4 [get_ports {ddr2_dq[13]}]
set_property src_info {type:SCOPED_XDC file:4 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V1 [get_ports {ddr2_dq[14]}]
set_property src_info {type:SCOPED_XDC file:4 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T3 [get_ports {ddr2_dq[15]}]
set_property src_info {type:SCOPED_XDC file:4 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N6 [get_ports {ddr2_addr[12]}]
set_property src_info {type:SCOPED_XDC file:4 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K5 [get_ports {ddr2_addr[11]}]
set_property src_info {type:SCOPED_XDC file:4 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R2 [get_ports {ddr2_addr[10]}]
set_property src_info {type:SCOPED_XDC file:4 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N5 [get_ports {ddr2_addr[9]}]
set_property src_info {type:SCOPED_XDC file:4 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L4 [get_ports {ddr2_addr[8]}]
set_property src_info {type:SCOPED_XDC file:4 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N1 [get_ports {ddr2_addr[7]}]
set_property src_info {type:SCOPED_XDC file:4 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M2 [get_ports {ddr2_addr[6]}]
set_property src_info {type:SCOPED_XDC file:4 line:165 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P5 [get_ports {ddr2_addr[5]}]
set_property src_info {type:SCOPED_XDC file:4 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L3 [get_ports {ddr2_addr[4]}]
set_property src_info {type:SCOPED_XDC file:4 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T1 [get_ports {ddr2_addr[3]}]
set_property src_info {type:SCOPED_XDC file:4 line:180 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M6 [get_ports {ddr2_addr[2]}]
set_property src_info {type:SCOPED_XDC file:4 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P4 [get_ports {ddr2_addr[1]}]
set_property src_info {type:SCOPED_XDC file:4 line:190 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M4 [get_ports {ddr2_addr[0]}]
set_property src_info {type:SCOPED_XDC file:4 line:195 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R1 [get_ports {ddr2_ba[2]}]
set_property src_info {type:SCOPED_XDC file:4 line:200 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P3 [get_ports {ddr2_ba[1]}]
set_property src_info {type:SCOPED_XDC file:4 line:205 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P2 [get_ports {ddr2_ba[0]}]
set_property src_info {type:SCOPED_XDC file:4 line:210 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N4 [get_ports {ddr2_ras_n}]
set_property src_info {type:SCOPED_XDC file:4 line:215 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L1 [get_ports {ddr2_cas_n}]
set_property src_info {type:SCOPED_XDC file:4 line:220 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N2 [get_ports {ddr2_we_n}]
set_property src_info {type:SCOPED_XDC file:4 line:225 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M1 [get_ports {ddr2_cke[0]}]
set_property src_info {type:SCOPED_XDC file:4 line:230 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M3 [get_ports {ddr2_odt[0]}]
set_property src_info {type:SCOPED_XDC file:4 line:235 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K6 [get_ports {ddr2_cs_n[0]}]
set_property src_info {type:SCOPED_XDC file:4 line:240 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T6 [get_ports {ddr2_dm[0]}]
set_property src_info {type:SCOPED_XDC file:4 line:245 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U1 [get_ports {ddr2_dm[1]}]
set_property src_info {type:SCOPED_XDC file:4 line:251 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U9 [get_ports {ddr2_dqs_p[0]}]
set_property src_info {type:SCOPED_XDC file:4 line:257 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V9 [get_ports {ddr2_dqs_n[0]}]
set_property src_info {type:SCOPED_XDC file:4 line:263 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U2 [get_ports {ddr2_dqs_p[1]}]
set_property src_info {type:SCOPED_XDC file:4 line:269 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V2 [get_ports {ddr2_dqs_n[1]}]
set_property src_info {type:SCOPED_XDC file:4 line:274 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L6 [get_ports {ddr2_ck_p[0]}]
set_property src_info {type:SCOPED_XDC file:4 line:279 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L5 [get_ports {ddr2_ck_n[0]}]
set_property src_info {type:SCOPED_XDC file:4 line:284 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y7 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_out}]
set_property src_info {type:SCOPED_XDC file:4 line:285 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y5 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_out}]
set_property src_info {type:SCOPED_XDC file:4 line:286 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y6 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_out}]
set_property src_info {type:SCOPED_XDC file:4 line:287 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y4 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_out}]
set_property src_info {type:SCOPED_XDC file:4 line:291 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y6 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:4 line:292 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y4 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:4 line:296 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y7 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/out_fifo}]
set_property src_info {type:SCOPED_XDC file:4 line:297 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y5 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/out_fifo}]
set_property src_info {type:SCOPED_XDC file:4 line:298 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y6 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/out_fifo}]
set_property src_info {type:SCOPED_XDC file:4 line:299 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y4 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/out_fifo}]
set_property src_info {type:SCOPED_XDC file:4 line:301 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y6 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:4 line:302 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y4 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:4 line:304 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHY_CONTROL_X1Y1 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/phy_control_i}]
set_property src_info {type:SCOPED_XDC file:4 line:306 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_REF_X1Y1 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/phaser_ref_i}]
set_property src_info {type:SCOPED_XDC file:4 line:308 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y81 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:4 line:309 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y57 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:4 line:311 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PLLE2_ADV_X1Y1 [get_cells -hier -filter {NAME =~ */u_ddr2_infrastructure/plle2_i}]
set_property src_info {type:SCOPED_XDC file:4 line:312 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC MMCME2_ADV_X1Y1 [get_cells -hier -filter {NAME =~ */u_ddr2_infrastructure/gen_mmcm.mmcm_i}]
set_property src_info {type:SCOPED_XDC file:4 line:328 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells -hier -filter {NAME =~ *temp_mon_enabled.u_tempmon/* && IS_SEQUENTIAL}] -to [get_cells -hier -filter {NAME =~ *temp_mon_enabled.u_tempmon/device_temp_sync_r1*}] 20
set_property src_info {type:SCOPED_XDC file:4 line:329 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells -hier *rstdiv0_sync_r1_reg*] -to [get_pins -filter {NAME =~ */RESET} -of [get_cells -hier -filter {REF_NAME == PHY_CONTROL}]] -datapath_only 5
set_property src_info {type:SCOPED_XDC file:4 line:332 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells -hier -filter {NAME =~ *ddr2_infrastructure/rstdiv0_sync_r1_reg*}] -to [get_cells -hier -filter {NAME =~ *temp_mon_enabled.u_tempmon/xadc_supplied_temperature.rst_r1*}] 20
set_property src_info {type:SCOPED_XDC file:5 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.1
set_property src_info {type:XDC file:6 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A3 [get_ports {red[0]}]
set_property src_info {type:XDC file:6 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B4 [get_ports {red[1]}]
set_property src_info {type:XDC file:6 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C5 [get_ports {red[2]}]
set_property src_info {type:XDC file:6 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A4 [get_ports {red[3]}]
set_property src_info {type:XDC file:6 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C6 [get_ports {green[0]}]
set_property src_info {type:XDC file:6 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A5 [get_ports {green[1]}]
set_property src_info {type:XDC file:6 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B6 [get_ports {green[2]}]
set_property src_info {type:XDC file:6 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A6 [get_ports {green[3]}]
set_property src_info {type:XDC file:6 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B7 [get_ports {blue[0]}]
set_property src_info {type:XDC file:6 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C7 [get_ports {blue[1]}]
set_property src_info {type:XDC file:6 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D7 [get_ports {blue[2]}]
set_property src_info {type:XDC file:6 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D8 [get_ports {blue[3]}]
set_property src_info {type:XDC file:6 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B11 [get_ports hsync]
set_property src_info {type:XDC file:6 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B12 [get_ports vsync]
set_property src_info {type:XDC file:6 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C17 [get_ports pwdn]
set_property src_info {type:XDC file:6 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G16 [get_ports OV7670_VSYNC]
set_property src_info {type:XDC file:6 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H14 [get_ports OV7670_SIOC]
set_property src_info {type:XDC file:6 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G13 [get_ports OV7670_HREF]
set_property src_info {type:XDC file:6 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H16 [get_ports OV7670_SIOD]
set_property src_info {type:XDC file:6 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E17 [get_ports {OV7670_D[0]}]
set_property src_info {type:XDC file:6 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D18 [get_ports {OV7670_D[1]}]
set_property src_info {type:XDC file:6 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F18 [get_ports {OV7670_D[2]}]
set_property src_info {type:XDC file:6 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E18 [get_ports {OV7670_D[3]}]
set_property src_info {type:XDC file:6 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G18 [get_ports {OV7670_D[4]}]
set_property src_info {type:XDC file:6 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G17 [get_ports {OV7670_D[5]}]
set_property src_info {type:XDC file:6 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E16 [get_ports {OV7670_D[6]}]
set_property src_info {type:XDC file:6 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D14 [get_ports {OV7670_D[7]}]
set_property src_info {type:XDC file:6 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D17 [get_ports reset_1]
set_property src_info {type:XDC file:6 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F16 [get_ports OV7670_PCLK]
set_property src_info {type:XDC file:6 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN F13 IOSTANDARD LVCMOS33} [get_ports OV7670_XCLK]
set_property src_info {type:XDC file:6 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN N17 IOSTANDARD LVCMOS33} [get_ports BTNC]
set_property src_info {type:SCOPED_XDC file:7 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells gen_fifo_generator.fifo_generator_inst/inst_fifo_gen/gaxis_fifo.gaxisf.axisf/grf.rf/gntv_or_sync_fifo.gcx.clkx/rd_pntr_gc_reg[*]] -to [get_cells gen_fifo_generator.fifo_generator_inst/inst_fifo_gen/gaxis_fifo.gaxisf.axisf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gsync_stage[*].wr_stg_inst/Q_reg_reg[*]] -datapath_only [get_property -min PERIOD [get_clocks -of_objects [get_pins design_1_i/axis_data_fifo_0/inst/m_axis_aclk]]]
set_property src_info {type:SCOPED_XDC file:7 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells gen_fifo_generator.fifo_generator_inst/inst_fifo_gen/gaxis_fifo.gaxisf.axisf/grf.rf/gntv_or_sync_fifo.gcx.clkx/wr_pntr_gc_reg[*]] -to [get_cells gen_fifo_generator.fifo_generator_inst/inst_fifo_gen/gaxis_fifo.gaxisf.axisf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gsync_stage[*].rd_stg_inst/Q_reg_reg[*]] -datapath_only [get_property -min PERIOD [get_clocks -of_objects [get_pins design_1_i/axis_data_fifo_0/inst/s_axis_aclk]]]
set_property src_info {type:SCOPED_XDC file:8 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [filter [all_fanout -from [get_ports s_axi_aclk] -flat -endpoints_only] {IS_LEAF}] -to [filter [all_fanout -from [get_ports m_axi_aclk] -flat -only_cells] {IS_SEQUENTIAL && (NAME !~ *dout_i_reg[*])}] -datapath_only [get_property -min PERIOD [get_clocks -of_objects [get_pins design_1_i/axi_mem_intercon/m00_couplers/auto_cc/inst/s_axi_aclk]]]
set_property src_info {type:SCOPED_XDC file:8 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [filter [all_fanout -from [get_ports m_axi_aclk] -flat -endpoints_only] {IS_LEAF}] -to [filter [all_fanout -from [get_ports s_axi_aclk] -flat -only_cells] {IS_SEQUENTIAL && (NAME !~ *dout_i_reg[*])}] -datapath_only [get_property -min PERIOD [get_clocks -of_objects [get_pins design_1_i/axi_mem_intercon/m00_couplers/auto_cc/inst/m_axi_aclk]]]
set_property src_info {type:SCOPED_XDC file:8 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_disable_timing -from CLK -to O [filter [all_fanout -from [get_ports s_axi_aclk] -flat -endpoints_only -only_cells] {PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==LUTRAM}]
set_property src_info {type:SCOPED_XDC file:8 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_disable_timing -from CLK -to O [filter [all_fanout -from [get_ports m_axi_aclk] -flat -endpoints_only -only_cells] {PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==LUTRAM}]
