webtalk_init -webtalk_dir F:\\filter_vga_rc\\image_filter_test_bench.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Mar 20 23:22:21 2017" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2016.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2016.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "gp7gpeg3jvq185nsnm3iuui2nk" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2016.2_11" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "11" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1490065334458" -context "sdk\\\\hardware/1490065334458"
webtalk_add_data -client sdk -key isZynq -value "false" -context "sdk\\\\hardware/1490065334458"
webtalk_add_data -client sdk -key Processors -value "1" -context "sdk\\\\hardware/1490065334458"
webtalk_add_data -client sdk -key VivadoVersion -value "2016.2" -context "sdk\\\\hardware/1490065334458"
webtalk_add_data -client sdk -key Arch -value "artix7" -context "sdk\\\\hardware/1490065334458"
webtalk_add_data -client sdk -key Device -value "7a100t" -context "sdk\\\\hardware/1490065334458"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1490065334458"
webtalk_add_data -client sdk -key uid -value "1490065622550" -context "sdk\\\\bsp/1490065622550"
webtalk_add_data -client sdk -key hwid -value "1490065334458" -context "sdk\\\\bsp/1490065622550"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1490065622550"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\bsp/1490065622550"
webtalk_add_data -client sdk -key uid -value "1490065642094" -context "sdk\\\\application/1490065642094"
webtalk_add_data -client sdk -key hwid -value "1490065334458" -context "sdk\\\\application/1490065642094"
webtalk_add_data -client sdk -key bspid -value "1490065622550" -context "sdk\\\\application/1490065642094"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1490065642094"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1490065642094"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1490065642094"
webtalk_transmit -clientid 3457294186 -regid "" -xml F:\\filter_vga_rc\\image_filter_test_bench.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html F:\\filter_vga_rc\\image_filter_test_bench.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm F:\\filter_vga_rc\\image_filter_test_bench.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
