# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/image_filter/image_filter.cache/wt [current_project]
set_property parent.project_path F:/image_filter/image_filter.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  F:/image_filter/image_filter.srcs/sources_1/new/serial_filter.v
  F:/image_filter/image_filter.srcs/sources_1/new/image_filter_top.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top image_filter_top -part xc7a100tcsg324-1


write_checkpoint -force -noxdef image_filter_top.dcp

catch { report_utilization -file image_filter_top_utilization_synth.rpt -pb image_filter_top_utilization_synth.pb }
